# This is a basic workflow to help you get started with Actions
name: Build artifact

# Controls when the action will run. 
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Do the build step
      - name: run the buildscript
        run: /bin/sh build-static-tmux.sh
      # Do the upload step
      - name: Upload artifacts
        uses: ncipollo/release-action@v2
        with:
          artifacts: "/tmp/tmux-static/bin/tmux.*.gz"
          replacesArtifacts: true
          allowUpdates: true
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
